CREATE TABLE IF NOT EXISTS student (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   enrolledprogram VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS subject (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   academicyear INT NOT NULL
);